version: '3.1'

services:

  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    networks:
      - main-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - main-network

networks:
  main-network:
